### PR TITLE
Add etag support for assets

### PR DESCRIPTION
**Pull request by xn**
Grabbed code from:
https://github.com/hexpm/hexpm/

Allows us to etag any future schema and is aware of associations.
We could apply this page controllers, etc.

### CODE REVIEW

**Comment by xn** [comment]
@bcardarella I thought it was MIT. I'll have to can this. We'd have to license this under the Apache 2.0 and document changes.

**Comment by bcardarella** [comment]
@xn let's leave this open, I've asked permission if we can use this code outside the license requirements. Let's see if that can be done before we abandon

**Comment by leandrocp** [comment]
AFAIK you can reuse and redistribute that code as long as you keep a header mentioning the original source, copyright, and license. Something like:

```elixir
# Copied and modified from the original work available at https://github.com/hexpm/hexpm/blob/d5b4e3864e219dd8b2cca34570dbe60257bcc547/lib/hexpm_web/controllers/controller_helpers.ex
# Copyright 2015 Six Colors AB
# Licensed under Apache 2.0 available at https://www.apache.org/licenses/LICENSE-2.0

defmodule BeaconWeb.Cache do
...
end
```

**Comment by bcardarella** [comment]
Eric has given permission so we're good
Screenshot 2023-06-28 at 1 40 45 PM

**Pull request merged**
