### PR TITLE
Make paths configurable

### PR DESCRIPTION
**Pull request by mayel**

### CODE REVIEW

**Comment by TheFirstAvenger** [comment]
Thanks for adding this. Can you modify it so `Application.get_env` doesn't appear in the template, and we call Application.get_env from the `.ex` file instead?

**Comment by mayel** [comment]
Does putting it in Util like this work for you?

**Review by TheFirstAvenger — APPROVED** [review]

**Comment by mayel** [comment]
@TheFirstAvenger done

**Comment by leandrocp** [comment]
Hey @mayel thank you so much for your PR. Can you please rebase with main?

**Pull request closed without merging**
